//let a = 5;
//let b ="34";
//console.log(a+b);
//let a = 5;
//let b ="4";
//console.log(a-b);
//let a = 10;
//let b =5;
//console.log(a%b);
//let a = 5;
//let b ="4";
//console.log(a-b);
//let a=5;
//let b=10;
//console.log(a%b)
//let a = "java";
//let b ="script";
//console.log(a+b);
//let a = "";
//let b ="";
//console.log(a+b);
//let a = "";
//let b =0;
//console.log(a+b);
//let a = true;
//let b = true;
//console.log(a+b);
//let d = true;
//let e = false;
//console.log(d+e);
//let a = false;
//let b = true;
//console.log(a-b);
//let a = 3;
//let b = 4;
//console.log(a-b);
//let a = "bob";
//let b = "bill";
//console.log(a-b);